### ISSUE TITLE
Basic Instruction

### ISSUE THREAD

**Issue by IamTaoChen** [lantongxue/rustdesk-api-server-pro#1]
Hi, can you write a basic document to introduce this project? e.g. how to use and develop it. I'd like to use it and maybe can help you implement this project.

Currently, I'm using this project: https://github.com/kingmo888/rustdesk-api-server

**Comment by lantongxue** [comment]
Hello,Thank you for your interest in this project, I will be updating README.md soon, please give me some time!

And I see your nickname looks like a Chinese person, if you are Chinese you can contact me on wechat, my wechat is: new-record

**Comment by lantongxue** [comment]
@IamTaoChen Hi, the project basics documentation has been updated! [docs](https://github.com/lantongxue/rustdesk-api-server-pro)

**Comment by IamTaoChen** [comment]
> @IamTaoChen Hi, the project basics documentation has been updated! [docs](https://github.com/lantongxue/rustdesk-api-server-pro)

thanks
