### ISSUE TITLE
使用RSA key後，登入api server會timeout

### ISSUE THREAD

**Issue by flier268** [lantongxue/rustdesk-api-server-pro#11]
不知道你有沒有解法，如果使用非RSA加密，就會變成未加密連線

目前我有的線索是：
https://github.com/lejianwen/rustdesk-api?tab=readme-ov-file#%E9%93%BE%E6%8E%A5%E4%B8%8D%E4%B8%8A%E6%98%AF%E6%88%96%E8%80%85%E8%B6%85%E6%97%B6
但他提出的解法都很麻煩，我覺的應該是伺服器沒有回應client，官方的pro server不知道用了什麼妖術

**Comment by lantongxue** [comment]
暂无解决方案
