### ISSUE TITLE
目前使用体验反馈

### ISSUE THREAD

**Issue by Kbstsn** [lantongxue/rustdesk-api-server-pro#12]
希望增加的功能
1、日志审计希望分为连接日志和文件传输日志，原本行为中的new和close两条记录进行合并，使用创建时间和结束时间进行表示。
2、增加客户端设备统计信息,包括设备信息，最后上线以及历史的ip和地址等
3、最好能够使用mysql等外部数据库。
bug部分
1、新版本种的容器目录映射似乎有bug，无法挂载成功。
2、登录页面验证码输错后无法自动更新验证码，需手动点击更新
3、登录界面无法使用回车键进行登录
4、审计日志中翻页功能存在bug，例如总日志为14条，仅能看见id为5-14的日志，无法进行翻页，且设置每页显示数量无效

**Comment by lantongxue** [comment]
感谢你的使用反馈。
关于新功能
1. 目前有很多计划在进行中，包括日志审计，设备管理，系统设置等
2. 系统原生支持mysql，只需要在配置文件中修改即可

关于bug
1. 容器映射的本质是把本地文件同步到容器中（这不算bug），所以直接挂载/app目录是不行的，会导致启动脚本找不到启动程序从而报错，后面我会考虑把主程序、数据库文件、配置文件分离开来，确保可以实现正常的挂载
2. 其余问题都会逐一解决


再次感谢你的反馈！

**Comment by lantongxue** [comment]
已经修复了[bug fix](https://github.com/lantongxue/rustdesk-api-server-pro/commit/19e873313ae783b4d823ebc45884c15b92fbc2b8)
