### ISSUE TITLE
Can you use rustdesk-api-server-pro with rustdesk-server (hbbs and hbbr) running on another container?

### ISSUE THREAD

**Issue by innovara** [lantongxue/rustdesk-api-server-pro#14]
Hi,

It's not an issue, but I don't think there is anywhere else I can post a question I have. I am still getting my head around how the API interacts with `rustdesk-server` so forgive me if it's a silly one.

I have checked the documentation and reviewed the code of `rustdesk-api-server-pro` and it seems to me that it is expected to run on the same host / docker container as `rustdesk-server`. Is that the case or am I missing something? Ideally, I would like to keep `rustdesk-server` running on its own containers. My gut feeling is that `rustdesk-api-server-pro` needs direct access to the binaries in order to perform its operations but I wanted to ask before ruling that option out.

Thanks.

**Comment by lantongxue** [comment]
I originally planned to host the running of hbbr/hbbs in rustdesk-api-server-pro, the relevant functionality has not been developed yet, the project has code to download and run hbbr/hbbs from github, and the relevant functionality will be implemented in the future.

Your docker compose file doesn't seem to be a problem, I'll be adapting it step by step!

**Comment by innovara** [comment]
Thanks. It's possibly a good idea to start thinking about placing `server.yaml` and `server.db` on a folder of their own inside the container, which can be mounted as a docker volume for persisting storage on the host, like `hbbs` does for the db and key. Other configuration files that should survive recreating the container should go there too. People are going to want to preserve the users that they created and so on, back that up, etc.

**Comment by lantongxue** [comment]
Yes, the containers themselves support mounting data and configurations out for permanent storage, and future practices will integrate hbbr/hbbs and be able to manage this via web-ui.
