### ISSUE TITLE
Verification Code?

### ISSUE THREAD

**Issue by mpetereit** [lantongxue/rustdesk-api-server-pro#3]
Hello :)

iam not sure what iam doing wrong here. The backend is running and the frontend too.

When I open the Frontend it tells me to put an authentication code and the image on the right is missing.
![image](https://github.com/user-attachments/assets/1dbf4fcc-99e6-47c2-babf-0f7fdfcc0947)

when i try to click on the broken image it tells me "api.the backend request error"

I guess there is still something i need to configure but iam not sure where...

**Comment by lantongxue** [comment]
see #2
