### ISSUE TITLE
Assistance Needed with Frontend Issues and Backend Connection

### ISSUE THREAD

**Issue by InformaticaRomar** [lantongxue/rustdesk-api-server-pro#4]
Hi 
I hope this message finds you well. First of all, I want to thank you for the excellent work you've done with this open-source project. I have successfully compiled the backend, but I'm experiencing some issues with the frontend that I hope you can help me resolve.

Firstly, I'm having trouble with the captcha. When attempting to load the image, I get the following error in Nginx:

> open() "/var/www/html/auth/captcha" failed (2: No such file or directory), client: 192.168.110.1, server: 127.0.0.1, request: "GET /auth/captcha HTTP/1.1", host: "192.168.110.196", referrer: "http://192.168.110.196/login"

I've temporarily bypassed this issue by editing the pwd-login.vue file and removing the captcha control, but I'd like to find a more appropriate solution.

Additionally, when trying to log in from the frontend, I encounter the following error message: api.the backend request error.

Attached is my current Nginx configuration in /etc/nginx/sites-available/default:

> server {
    listen 80;
    server_name localhost;
    location / {
            index /index.html;
            root /var/www/html;
            try_files $uri $uri/ /index.html;
        }
#PROXY-START /api for rustdesk client
    location /api/ {
       proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_http_version 1.1;
       add_header X-Cache $upstream_cache_status;
    }
    #PROXY-END/ 
 #PROXY-START /admin for web-ui
    location /admin{
        proxy_pass http://127.0.0.1:8080/admin;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header REMOTE-HOST $remote_addr;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_http_version 1.1;
        add_header X-Cache $upstream_cache_status;
    }
    #PROXY-END/
}

My impression is that the frontend is not properly connecting to the backend. When I make the following request using curl:

> curl -X POST http://localhost:8080/api/login \
     -H "Content-Type: application/json; charset=utf-8" \
     -d '{
           "username":"kali",
           "password":"123456",
           "id":"216456628",
           "uuid":"OWFlNTA4YjQtZWVjYy00MjU0LThiYmItNTRjYjVmYTRkNDJl",
           "autoLogin":true,
           "type":"account",
           "deviceInfo":{
              "os":"windows",
              "type":"client",
              "name":"desktop-s11sceo"
           }
         }'

The backend receives and processes the request correctly, as shown in the logs:

> [INFO] 2024/09/26 13:08 ▶ POST:/api/login
Content-Type: [application/json; charset=utf-8]
Content-Length: [370]
User-Agent: [curl/7.81.0]
Accept: [*/*]

However, when attempting the same process through the frontend, I don't receive any response.

Any guidance or advice you can provide would be greatly appreciated. I'm sure I'm overlooking some detail, but I haven't been able to find the solution on my own.

Thank you in advance for your help and time!

**Comment by lantongxue** [comment]
Refer to this:
```nginx
#PROXY-START /api for rustdesk client
location ^~ /api
{
    proxy_pass http://127.0.0.1:8080;
    proxy_set_header Host 127.0.0.1;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    # proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;
}
#PROXY-END/
```
`/api` is not followed by `/`

**Comment by InformaticaRomar** [comment]
Thank you very much for your quick response. I have made the change you indicated, but I continue to have problems.

>  api.the backend request error

I'm compiling in Ubuntu, any ideas, any solutions?

`pnpm i
Scope: all 9 workspace projects
Lockfile is up to date, resolution step is skipped
Already up to date
. prepare$ simple-git-hooks
│ [INFO] Successfully set all git hooks
└─ Done in 180ms
Done in 5.9s`

`pnpm build

> soybean-admin@1.3.4 build /home/administrador/rustdesk/rustdesk-api-server-pro/soybean-admin
> vite build --mode prod



Building [████████████████████████████████████████] 100% | Transforms: 3585/3585 | Chunks: 17/17 | Time: 71.1s

Build successful. Please see dist directory
`

**Comment by lantongxue** [comment]
I'm guessing it's still a problem with your nginx configuration.

**Comment by InformaticaRomar** [comment]
this is my complete nginx.conf configuration,  

> user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
       
}

http {



        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        map $http_upgrade $connection_upgrade {
           default upgrade;
           ''      close;
       }

        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

      
        gzip on;
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

I have no problem changing it, completely, can you send me the configuration that works for you?
 please
 
 Thanks in advance

**Comment by lantongxue** [comment]
see #2

**Comment by InformaticaRomar** [comment]
I have performed several tests:

I downloaded again the latest version
Recompiled the code 
without ngnix configuration


Configured the ngnix.conf configuration indicated:

```
worker_processes 1;

events { worker_connections 1024; }

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;


   
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    server {
        listen 80;
        server_name localhost;

        # Configuración para el proxy /api
        location ^~ /api {
                        proxy_pass http://127.0.0.1:8080;
                        proxy_set_header Host 127.0.0.1;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header REMOTE-HOST $remote_addr;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection $connection_upgrade;
                        proxy_http_version 1.1;
                        # proxy_hide_header Upgrade;

                        add_header X-Cache $upstream_cache_status;
        }

        # Configuración para el proxy /admin
        location ^~ /admin {
                        proxy_pass http://127.0.0.1:8080/admin;
                        proxy_set_header Host 127.0.0.1;
                        proxy_set_header X-Real-IP $remote_addr;
                        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                        proxy_set_header REMOTE-HOST $remote_addr;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection $connection_upgrade;
                        proxy_http_version 1.1;
                        # proxy_hide_header Upgrade;

                        add_header X-Cache $upstream_cache_status;
                }

        # Configuración para servir archivos estáticos
        location / {
            root /var/www/html;
            index index.html;
                        try_files $uri $uri/ /index.html;
        }
    }
}

```
I downloaded again the latest version
Recompiled the code 


I have tried varying the order of compilation, configuration etc and nothing.

In no case it worked for me

**Comment by lantongxue** [comment]
try remove this code `try_files $uri $uri/ /index.html;`

**Comment by InformaticaRomar** [comment]
I tried deleting try_files $uri $uri/ /index.html;
but the problem remains.
I have continued testing I have found that launching pnpm dev
works correctly
I have also seen that .env.prod was not filled in 
# backend service base url, prod environment
VITE_SERVICE_BASE_URL=/
I set .env.test as .env.test
VITE_SERVICE_BASE_URL=http://localhost:8080/admin
and now the problem is CORS Reason: CORS request unsuccessful).
I have tried to launch 
curl -H ‘Origin: http://localhost:8080/admin/auth/captcha’ http://localhost/
and it works correctly

> {"code":200,"data":{"id":"Qv0MEGAtGAdDRhdvjjzc","img":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAHgAAAAyCAIAAAAYxYiPAAAJsklEQVR4nOyaeXAT5xnGP0krS6v7Xu1Kso2N8YGBEJoQYhInJUAuSkgmA+OSZnokTEoyTTpJmgyNoUw6ZQJJadMU0mmGaUhCOmEg0BDTAROuQAwGY2xjgyVZhyV5dd8nkjprGdtdEypLXsXT6PfX7rva93t49vW377d8UG/4GihCPfTvWsD3haLRBaJodIEoGl0gikYXCIjqAULBgL6/36DXmU0Gs8Fgs1oCPh+m0az/9as1s+upHn36QKO6vXtsyb2ZA7FEqsQwlaaUDcNf7NvLZDJfad58590NlI4+faC8ogEAuz7bLxCKGAxG5tTn9X6xby+CYls3N2966+3Zc28rgIbvHMrnaCaTyeHyRl0GAAhFIpjDWfuzZxofWPaXbW9RLWCaQLnRMIfrdjlJQRRT+f3etT9/xmYZjITDVGuYDlButFQmsw0OkoKoSm2zWERiCZPJNA7oqdYwHaDcaCWmMg7oSEFMrbEOuy9HlN8Toyl/GSIoahwYIAVRlerksaPDjwEz6smPYVrhdeAWbR+Lw0knUzQGXVNVx+Jwc8hDudEKJXr54gVSUF1Whtus4VBIpSnVXbtKtYacMV3t3vnKulhk7C0C8/iPP//a/Psf9DqGxAiWfSrKpw65AjEbDalkcnxQpdYAAAZNRkytNhsNVGvImXOHP49FwjCPT6PRMpFIMPDxlg2nD/yzr/1MPBrJPhX1L0O5PJFI2KzW8UEujw9BkAPHS8tnBPx+n9dLtYzciEeiAICGH61+45PDS9c+s/zp5yAmEwBwYOc2pLTi7KG92acqQNchBwDYLGZSXCASOZ32GZVVAADcZqVaRm7EosSkEQ74ErGoB7ctbfrFqudfAwCkUymP3ebBbdmnIhsd9iVMV/xWbTCVSk+JVqFIxGKxAn4/KS4SS5w4zuFymUxmOBSakrGmnESMqGihVB7wuO578ic0On3hQ6tYMIcIyhR8sdTvcmSZauxlqL3o2bP5SvcpZzpNWMyXlDz20qwV62fmL1cik3s9HlJQKBLZcRwAwIbhcHiaGh0bXkwhZZWpZJLJYgMAaDSaXF062N9n6usWK9Cg1y2QyrNJNVLRJ/aYfrv8ZNdJB8yHZi+WC6SsgDu++43uXa935S9XplD4feRZmKhohz1jdCgYzH8UKrieiAEAStgjFt8IEwcOs5HJZkMlrCxTEUb3nXXteKEjlUxLMHj7uQc2Hmx4r3NZ7SIpAKDlfd2pz8jruskilcndLhcpyBcI7EPEHMfnC6at0alkKnNAYzCYNzzNdHvRcNDvcsI8fpapCKM/+l1PZkZ+6NkKkYJIx+Iw1m2fn/nFnjev5DlfS2Uy13DxjkcgFAb8/mg0IpHJJtZ79jg8tu7+9l59RyDsy0fkTWEM9xghn1cglnIEQgBA8nrCZSMqjwVzI0E/VyjKMhUUcMevnXNnTuYvQUYvYFW8inkifafXaQ63twzd+Qias1yxVOpxkyuay+MBAOxDQwolah0k9yTZkE6nW9sOao09bBYcjUXodHrjHQ9Xl8/NWedEMgXLZLNlqtJMpOfsicyaQDWzxmk10emMLFNBLstY1y1C/mvGqVkk1XcStdZ1wpGP0TKZwuN2k4ISqYyoRxyvqav/+3t/TiTiNovFoNOZjQbroBm3WZ0Oe8DvZ7HZT/74qVWrmyam1Zl7tcae+qoFi29f3m/saf3mwMn2lnJsFquEnbNUEololFnCmjV/YTqdDvu9+q6Ofe/+IfMApJhqUqkgqGSswwsHrgtkY16rqkYmoP7zZJsmhVyJhEOhWCzGYo0lV5eWAwDa285CDIbf5139yPJ0KlVeUVk3d96ddzeUzahAUAzmcNq/OfPmhtccdvuzL7xIShsfflOhcqLWStEK4u86mQxF/FNodNDnSSavf9D8or7rYjo1Ml8LZYrVL286tX/P081bs08FoZU8FgeKha8THd4Fj3LG2BeT0QJ3WSex1pyIHFECAJx2u0qjGQ2qNJqFDff4PB6hWPzT59bPqJxZVV0LczikeytnVc+srvF5PCdajzQuWTr+Ul3lbRKhHJESlWWxG4l/DAMS8CT5SCVRvWDR6QOf6jrbM6cMBvSDZSuWPbXu3x/ueOy5l5lZtxwZbbRFK7Hje0wAgC/f1zU8oc60MalU+tJRPPOjkDeRj1yBQMiGYbfTMd5oAMDrm3//P+8VS6Qwh/PgipWffriLZDQANKVMTTRhyURb51fEXFcxD2JM5Weylb98+fYlDydiUToEgXSaTqfjZkPf+a9Xrf9NCRueVCpC1poNdecO2cL+hPaCZ8vqs4uf1IR9idbdBkPXjfc4LV/FcgSx40O53cvlcjXl5YZv/5p6/PyXvqBHIpTfNe+HeWi8CXQ6o6x2TuY4nUppL52/Y+mj9JyeJXGPBGO/+vFd255qC3rjHUfxjuFCLmEz5i9FOo4QxzxRSZ6KlSjmnNDh3QK302mzWuxDNtxmG7JaWw+38AUCm9WCTngF9WgvaI09fK7wkcY1EIOZp85bQKPTq25fmPPtIw+nrkH6x7Ylxz8xGbp8DCataoGk4QlV++GhjNGammzb8m8DVakHTaabXkomk4Mmo1GvHzQZTIYBy6B5yGpNxOPjf2PQ69gwbDYYSEbb3davO47CbO6K+5q4cL4iKWXsr0AoZ638VdX4awOdI+uI2rtleQ6DqlSnv2odPXXacV3/te5LHb093cYBPcnWmxKNREyGgfH7QGLx6JEz+yEG9GjjGgFPnKdCqrnVdHOp1Z5Z49/XVJrnMJqycrfLtXP72xazSa/VhoKBHJLEh7+ljXKs7WAoHFhxf5NUNLLO8gZcOnPvgrrFeaqlAsLo9pahf2zoqr9Hvu5PY3tZOo7iNl0QAHDvGo1MPbk37ESqqmtlcsXhfx3I/hY6g4EoUYVSKVcgCiVaN2fO+K02OnOv0aql0+k92otXdJeGF4opo1U7u2pBnlIpgjB63ztXcUMIN4TqG+UNjxOToN8V/+CVy0QrrWCv3TQ7/2FYbPbGLds2vvrSxK9LmatKFEMwDEGUCIahmBpVqRAUG7/thkQsHqHRaKlUSmu6MhqUCOXTs5xH9t59tLHn4Lv9RKcBMx5eV8nmQsd2G+ymMF9S0vz54rJ6wVQN5nY5//rO1ssXL6jLyuvmzK2urUPVGoVSKRj+XvP/DWF0KpU+tEPX8je90zzy370wH1q0UtXUXDd+RV4kH8Z2k6bTADeEPLYoX1qClHOZrOLW6amE8m27RTIUy7ZAFI0uEEWjC0TR6AJRNLpAFI0uEEWjC0TR6AJRNLpAFI0uEEWjC8R/AgAA///WtLviDaCsSgAAAABJRU5ErkJggg=="},"message":"ok"}


 so I deduce that it could be a frontend problem, any idea?

**Comment by lantongxue** [comment]
For production environments, it is sufficient to keep `VITE_SERVICE_BASE_URL=/`, as all requests will start at `/` by default.

After setting up the reverse proxy, you can make normal requests without cross-domain issues.

**Comment by lantongxue** [comment]
I don't think you're really solving the problem.

`VITE_SERVICE_BASE_URL=/ `means you need to set up a reverse proxy for `nginx`.
Let's say the server listens on port `127.0.01:8080`
Then `http://localhost:8080/admin/auth/captcha` is the real server address.

`nginx` then needs to reverse proxy `http://127.0.01:8080`.

Then the request sent in the browser will be `http://your-domain/admin/auth/captcha` instead of `http://your-ip:8080/admin/auth/captcha`

**Of course, if you'd rather just expose the ip address and port request that's fine too (not recommended)**

**Comment by InformaticaRomar** [comment]
I'll keep trying things, for the moment I'll mount the reverse proxy in apache2 to see if it works.

**Comment by paintballkev812** [comment]
Also having this issue. Set up Nginx reverse proxy using the information provided, but captcha does not load and  api.request failed with error 404 error message. Reverse proxy seems to be working as if I try to browse directly to /api or /admin, I can see an INFO log entry in the backend console. Is there any configuration needed on the frontend before building?

**Comment by lantongxue** [comment]
@paintballkev812 No special settings required

**Comment by paintballkev812** [comment]
Looking more, It appears the captcha is trying to load from <weburl>/auth/captcha, but no auth folder exists  in dist when built. Additionally, looking at the reverse proxy sample, there are only entries for api and admin. Should I expect to find an /auth path in dist or should a reverse proxy be set for /auth?

**Comment by lantongxue** [comment]
The latest code has now been released

**Comment by paintballkev812** [comment]
will pull latest code and try again

**Comment by paintballkev812** [comment]
Working as expected now, thanks!
