### ISSUE TITLE
请问有计划支持Docker吗

### ISSUE THREAD

**Issue by rayangl** [lantongxue/rustdesk-api-server-pro#5]
好好看的界面，看起来就很强，能支持arm64吗

**Comment by lantongxue** [comment]
有计划支持的，目标是支持主流系统（Windows、macOS、Linux）及架构（x86_64、arm64）

**Comment by rayangl** [comment]
期待

**Comment by lantongxue** [comment]
等这次把两步验证加上后就准备支持Docker和主流系统架构了

**Comment by rayangl** [comment]
不错不错，太厉害了😏

**Comment by lantongxue** [comment]
docker镜像现已正式发布
[https://github.com/lantongxue/rustdesk-api-server-pro/pkgs/container/rustdesk-api-server-pro](https://github.com/lantongxue/rustdesk-api-server-pro/pkgs/container/rustdesk-api-server-pro)

**Comment by lantongxue** [comment]
docker文档已更新
