### ISSUE TITLE
The control end need to login before access

### ISSUE THREAD

**Issue by blackxd0g** [lantongxue/rustdesk-api-server-pro#6]
Hello. Rustdesk api pro has a useful feature in the settings.
The control end need to login before access. Is it possible to add this functionality?

**Comment by lantongxue** [comment]
Can you elaborate (demonstrate) this feature?

**Comment by blackxd0g** [comment]
If the user is not logged in, he receives an error when connecting to any device in which the RustDesk server is registered.
You need to be logged in only for outgoing connections.
![image](https://github.com/user-attachments/assets/5ab0b0e2-3887-4dbf-84d6-65038ec86c06)
![image](https://github.com/user-attachments/assets/68130857-577e-43e9-abc5-570c53ee313a)

This setting is linked to the device IDs that fall into the default group after the server settings have been registered.. You can also link individual devices to individual groups and specify which group of users has access to them.

**Comment by lantongxue** [comment]
These features may not be possible, but I'll try!
