### ISSUE TITLE
Linux兼容

### ISSUE THREAD

**Issue by Kbstsn** [lantongxue/rustdesk-api-server-pro#7]
只能编译成Windows的吗？

**Comment by lantongxue** [comment]
可以编译成Linux的二进制文件，参考golang的编译方式。

**Comment by Kbstsn** [comment]
希望能提供编译好的版本，不然还得花好久的时间配置编译环境。

**Comment by lantongxue** [comment]
docker镜像现已正式发布
[https://github.com/lantongxue/rustdesk-api-server-pro/pkgs/container/rustdesk-api-server-pro](https://github.com/lantongxue/rustdesk-api-server-pro/pkgs/container/rustdesk-api-server-pro)

**Comment by rayangl** [comment]
> docker镜像现已正式发布 https://github.com/lantongxue/rustdesk-api-server-pro/pkgs/container/rustdesk-api-server-pro

有compose文件吗 我是arm64的硬件

**Comment by Kbstsn** [comment]
没文档，不知道支持哪些环境变量，不知道怎么添加用户（笑哭）。

**Comment by lantongxue** [comment]
文档后续会补上

**Comment by lantongxue** [comment]
文档已经更新，请看README.md

**Comment by lantongxue** [comment]
已更新支持arm64架构的docker镜像
