### ISSUE TITLE
哇，docker来了，感谢作者大大，支持作者大大

### ISSUE THREAD

**Issue by hexsen929** [lantongxue/rustdesk-api-server-pro#9]
哇，docker来了，感谢作者大大，支持作者大大。

**Comment by lantongxue** [comment]
感谢支持

**Comment by lantongxue** [comment]
docker文档已更新

**Comment by hexsen929** [comment]
> docker文档已更新

`docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/rustdesk-api-server-pro": stat /app/rustdesk-api-server-pro: no such file or directory: unknown.`

大大，不知道为啥，不能挂载/app目录出来，不挂载的话就没有问题。，换成composer部署也不能挂载出来

**Comment by hexsen929** [comment]
`root@song-Standard-PC-Q35-ICH9-2009:/home/song# docker exec -it rustdesk-api-server-pro ls -l /apptotal 42132
drwxr-xr-x    3 root     root          4096 Oct 11 14:56 dist
-rwxr-xr-x    1 root     root      43072225 Oct 11 14:56 rustdesk-api-server-pro
-rw-r--r--    1 root     root         61440 Oct 11 14:56 server.db
-rw-r--r--    1 root     root           460 Oct 11 14:55 server.yaml`

我不挂载出来，进去看了是有文件的，奇怪了

**Comment by lantongxue** [comment]
目前挂载不了这个目录，只能在本地先准备好server.yaml
然后`-v /your/path/server.yaml:/app/server.yaml`

**Comment by hexsen929** [comment]
> 目前挂载不了这个目录，只能在本地先准备好server.yaml 然后`-v /your/path/server.yaml:/app/server.yaml`

收到
